import type { NitroPluginEvlogConfig } from '../nitro'
import { layerEvlogConfig } from './configMerge'
import type { EvlogConfig } from './define'
import { toLoggerConfig } from './define'
import type { EvlogPlugin } from './plugin'
import { definePlugin } from './plugin'

/**
 * Global slot the plugin generated by the evlog Nitro and Nuxt modules fills
 * with the default export of `evlog.config.ts`. The generated plugin imports
 * nothing from evlog, so it reaches this runtime wherever Nitro resolved it from.
 */
export const EVLOG_FILE_CONFIG_KEY = 'evlog.config.file'

/** Name of the plugin that carries the `drain`, `enrich` and `keep` of `evlog.config.ts`. */
export const EVLOG_FILE_CONFIG_PLUGIN = 'evlog-config'

/** Settings the Nitro plugins read once `evlog.config.ts` and the module options are layered. */
export interface NitroRuntimeEvlogConfig extends NitroPluginEvlogConfig {
  stringify?: boolean
}

/** The default export of `evlog.config.ts` loaded into this server, if any. */
export function readEvlogFileConfig(): EvlogConfig | undefined {
  return (globalThis as Record<symbol, EvlogConfig | undefined>)[Symbol.for(EVLOG_FILE_CONFIG_KEY)]
}

/**
 * Lay the module options over `evlog.config.ts`: the file is the base, and
 * what `nuxt.config` or the Nitro module sets wins, merged with the
 * `extends` rules. Functions are left out: {@link evlogFileConfigPlugins}
 * carries them.
 */
export function withEvlogFileConfig(options: NitroPluginEvlogConfig | undefined): NitroRuntimeEvlogConfig | undefined {
  const file = readEvlogFileConfig()
  if (!file) return options
  const {
    extends: _extends,
    service: _service,
    environment: _environment,
    map: _map,
    logs: _logs,
    drain: _drain,
    enrich: _enrich,
    keep: _keep,
    plugins: _plugins,
    waitUntil: _waitUntil,
    ...settings
  } = file
  const { env } = toLoggerConfig(file)
  const base: NitroRuntimeEvlogConfig = env ? { ...settings, env } : settings
  return options ? layerEvlogConfig(base, options) : base
}

/**
 * The plugins of `evlog.config.ts`, plus one named `evlog-config` that runs
 * its `drain`, `enrich` and `keep` next to the `evlog:*` Nitro hooks.
 */
export function evlogFileConfigPlugins(): EvlogPlugin[] | undefined {
  const file = readEvlogFileConfig()
  if (!file) return undefined
  const { drain, enrich, keep } = file
  const hooks = drain || enrich || keep
    ? [definePlugin({ name: EVLOG_FILE_CONFIG_PLUGIN, drain, enrich, keep })]
    : []
  return [...(file.plugins ?? []), ...hooks]
}

/**
 * Flush the `drain` of `evlog.config.ts` when it buffers events, as a
 * `createDrainPipeline` drain does. The Nitro plugins call it on `close`.
 */
export async function flushEvlogFileConfigDrain(): Promise<void> {
  const drain = readEvlogFileConfig()?.drain as { flush?: () => Promise<void> } | undefined
  if (typeof drain?.flush === 'function') await drain.flush()
}
